quotes = [
    "Straight to the point, no time for hellos.",
    "Chat time is precious, skip the hellos.",
    "Greetings are nice, but let's dive into the chat.",
    "No time for hellos, let's get down to business.",
    "Skip the pleasantries, let's chat efficiently.",
    "In this chat, hellos can take a backseat.",
    "Save time, skip the hellos, and dive in.",
    "Hello? Let's cut to the chase and start the chat.",
    "Quick chats, no time for greetings.",
    "Efficiency is key, no time for hellos.",
    "Time is money, let's chat with purpose.",
    "Leave the hellos at the door, let's chat.",
    "Forget the greetings, let's make it worthwhile.",
    "Hi there, but let's get straight to business.",
    "Hello? Let's skip to the juicy part of the chat.",
    "No time for introductions, let's chat.",
    "Cut the small talk, let's chat like pros.",
    "Enough with the hellos, let's dive into the chat.",
    "Hi! Let's skip the formalities and chat.",
    "Save the greetings for later, let's chat now.",
    "Greetings aside, let's chat effectively.",
    "Quick chats, big impact, no time for hellos.",
    "Hello? Let's chat with purpose.",
    "Hello! Let's chat efficiently and achieve more.",
    "Efficient chats, no room for hellos.",
    "In this chat, hellos are overrated.",
    "Hello? Let's make every word count.",
    "No time for idle chit-chat, let's chat.",
    "Skip the hellos, let's make this chat count.",
    "Greetings can wait, let's chat.",
    "Get to the point, no time for hellos.",
    "Hi there! Let's get straight to business.",
    "Hello? Let's cut to the chase and make progress.",
    "No room for hellos, let's chat like pros.",
    "Greetings are nice, but let's chat effectively.",
    "Efficiency starts with skipping the hellos.",
    "Save time, skip the greetings, let's chat.",
    "Hi! Let's dive right into the chat.",
    "Leave the hellos behind, let's chat.",
    "No more hellos, let's make every chat count.",
    "Hello? Let's chat smart and get things done.",
    "Quick chats, no time for formalities.",
    "Enough with the greetings, let's chat productively.",
    "Greetings aside, let's focus on the chat.",
    "Cut the small talk, let's have a meaningful chat.",
    "Hello! Let's get down to business and chat.",
    "No time for hellos, let's achieve more.",
    "In this chat, hellos are not on the agenda.",
    "Hello? Let's have a chat that matters.",
    "No idle chit-chat, let's get to the point.",
    "Skip the hellos, let's make progress in this chat.",
    "Greetings can wait, let's get to the chat.",
    "Get to the point, no time for greetings.",
    "Hi there! Let's make this chat count.",
    "Hello? Let's cut to the chase and make a difference.",
    "No room for hellos, let's chat like professionals.",
    "Greetings are nice, but let's be efficient in our chat.",
    "Efficiency begins with skipping the hellos.",
    "Save time, skip the greetings, let's get to the chat.",
    "Hi! Let's dive into the chat headfirst.",
    "Leave the hellos behind and let's get to the chat.",
    "No more hellos, let's ensure every chat matters.",
    "Hello? Let's have a smart and productive chat.",
    "Quick chats, no time for formalities.",
    "Enough with the greetings, let's chat with purpose.",
    "Greetings aside, let's focus on the chat.",
    "Cut the small talk, let's have a valuable chat.",
    "Hello! Let's get straight to business and chat.",
    "No time for hellos, let's accomplish more in our chat.",
    "In this chat, hellos have no place.",
    "Hello? Let's have a chat that truly matters.",
    "No idle chit-chat, let's get right to it.",
    "Skip the hellos, let's make progress in this chat.",
    "Greetings can wait, let's dive into the chat.",
    "Get to the point, no time for greetings.",
    "Hi there! Let's make this chat impactful.",
    "Hello? Let's cut to the chase and make an impact.",
    "No room for hellos, let's chat like pros.",
    "Greetings are nice, but let's have an effective chat.",
    "Efficiency starts with skipping the hellos.",
    "Save time, skip the greetings, let's chat.",
    "Hi! Let's dive right into the chat.",
    "Leave the hellos behind, let's chat.",
    "No more hellos, let's make every chat count.",
    "Hello? Let's chat smart and get things done.",
    "Quick chats, no time for formalities.",
    "Enough with the greetings, let's chat productively.",
    "Greetings aside, let's focus on the chat.",
    "Cut the small talk, let's have a meaningful chat.",
    "Hello! Let's get down to business and chat.",
    "No time for hellos, let's achieve more.",
    "In this chat, hellos are not on the agenda.",
    "Hello? Let's have a chat that matters.",
    "No idle chit-chat, let's get to the point.",
    "Skip the hellos, let's make progress in this chat.",
    "Greetings can wait, let's get to the chat.",
    "Get to the point, no time for greetings.",
    "Hi there! Let's make this chat count.",
    "Hello? Let's cut to the chase and make a difference.",
    "No room for hellos, let's chat like professionals.",
    "Greetings are nice, but let's be efficient in our chat.",
    "Efficiency begins with skipping the hellos.",
    "Save time, skip the greetings, let's get to the chat.",
    "Hi! Let's dive into the chat headfirst.",
    "Leave the hellos behind and let's get to the chat.",
    "No more hellos, let's ensure every chat matters.",
    "Hello? Let's have a smart and productive chat.",
    "Quick chats, no time for formalities.",
    "Enough with the greetings, let's chat with purpose.",
    "Greetings aside, let's focus on the chat.",
    "Cut the small talk, let's have a valuable chat.",
    "Hello! Let's get straight to business and chat.",
    "No time for hellos, let's accomplish more in our chat.",
    "In this chat, hellos have no place.",
    "Hello? Let's have a chat that truly matters.",
    "No idle chit-chat, let's get right to it.",
    "Skip the hellos, let's make progress in this chat.",
    "Greetings can wait, let's dive into the chat.",
    "Get to the point, no time for greetings.",
    "Hi there! Let's make this chat impactful.",
    "Hello? Let's cut to the chase and make an impact.",
    "No room for hellos, let's chat like pros.",
    "Greetings are nice, but let's have an effective chat.",
    "Efficiency starts with skipping the hellos.",
    "Save time, skip the greetings, let's chat.",
    "Hi! Let's dive right into the chat.",
    "Leave the hellos behind, let's chat.",
    "No more hellos, let's make every chat count.",
    "Hello? Let's chat smart and get things done.",
    "Quick chats, no time for formalities.",
    "Enough with the greetings, let's chat productively.",
    "Greetings aside, let's focus on the chat.",
    "Cut the small talk, let's have a meaningful chat.",
    "Hello! Let's get down to business and chat.",
    "No time for hellos, let's achieve more.",
    "In this chat, hellos are not on the agenda.",
    "Hello? Let's have a chat that matters.",
    "No idle chit-chat, let's get to the point.",
    "Skip the hellos, let's make progress in this chat.",
    "Greetings can wait, let's get to the chat.",
    "Get to the point, no time for greetings.",
    "Hi there! Let's make this chat count.",
    "Hello? Let's cut to the chase and make a difference.",
    "No room for hellos, let's chat like professionals.",
    "Greetings are nice, but let's be efficient in our chat.",
    "Efficiency begins with skipping the hellos.",
    "Save time, skip the greetings, let's get to the chat.",
    "Hi! Let's dive into the chat headfirst.",
    "Leave the hellos behind and let's get to the chat.",
    "No more hellos, let's ensure every chat matters.",
    "Hello? Let's have a smart and productive chat.",
    "Quick chats, no time for formalities.",
    "Enough with the greetings, let's chat with purpose.",
    "Greetings aside, let's focus on the chat.",
    "Cut the small talk, let's have a valuable chat.",
    "Hello! Let's get straight to business and chat.",
    "No time for hellos, let's accomplish more in our chat.",
    "In this chat, hellos have no place.",
    "Hello? Let's have a chat that truly matters.",
    "No idle chit-chat, let's get right to it.",
    "Skip the hellos, let's make progress in this chat.",
    "Greetings can wait, let's dive into the chat.",
    "Get to the point, no time for greetings.",
    "Hi there! Let's make this chat impactful.",
    "Hello? Let's cut to the chase and make an impact.",
    "No room for hellos, let's chat like pros.",
    "Greetings are nice, but let's have an effective chat.",
    "Efficiency starts with skipping the hellos.",
    "Save time, skip the greetings, let's chat."
]